name: "Validate & Test"

on:
  pull_request:
    branches:
      - main
  
jobs: 
  validate:
    runs-on: ubuntu-latest
    env:
      working-directory: terraform
      TF_WORKSPACE: my-workspace
      AWS_REGION: "us-east-1"
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.working-directory }}
        continue-on-error: false
